# This workflow builds and publishes the extension to OpenVSX.
# It runs when a new tag (v*) is pushed.
name: Release to OpenVSX

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "**/v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      EXTENSION_PATH: ${{ vars.EXTENSION_PATH }}
      PUBLISHER_NAME: ${{ vars.PUBLISHER_NAME }}
      OPEN_VSX_TOKEN: ${{ secrets.OPEN_VSX_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect pnpm version
        id: detect-pnpm
        run: |
          if [ -f package.json ] && grep -q '"packageManager":' package.json; then
            echo "Found packageManager in root package.json"
            echo "version=" >> $GITHUB_OUTPUT
          elif [ -f "${{ env.EXTENSION_PATH }}/package.json" ] && grep -q '"packageManager":' "${{ env.EXTENSION_PATH }}/package.json"; then
            echo "Found packageManager in ${{ env.EXTENSION_PATH }}/package.json"
            echo "version=" >> $GITHUB_OUTPUT
          else
            echo "No packageManager found, using default version 10"
            echo "version=10" >> $GITHUB_OUTPUT
          fi

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.detect-pnpm.outputs.version }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Everything
        run: pnpm -r run build

      # Updates the 'publisher' field in package.json to match the environment variable.
      # The upstream package.json has the original publisher. We need to publish under YOUR publisher ID.
      - name: Patch to ${{ env.PUBLISHER_NAME }}
        run: |
          cd ${{ env.EXTENSION_PATH }}

          jq '.publisher = "${{ env.PUBLISHER_NAME }}"' package.json > package.json.tmp && mv package.json.tmp package.json

          echo "Publisher verified as:"
          grep '"publisher":' package.json

      # Runs 'vsce package' to create the file and 'ovsx publish' to upload it.
      # This creates the .vsix artifact and uploads it to the OpenVSX registry.
      - name: Build & Publish
        env:
          OVSX_PAT: ${{ env.OPEN_VSX_TOKEN }}
        run: |
          cd ${{ env.EXTENSION_PATH }}

          pnpm dlx vsce package

          pnpm dlx ovsx publish -p $OVSX_PAT || echo "Publish failed or version already exists."
